import type { Metadata } from "next";
import { routing } from "@/i18n/routing";

export const OG_LOCALES: Record<string, string> = {
  pl: "pl_PL",
  en: "en_US",
  uk: "uk_UA",
};

// Metadata for an inner page (service pages, privacy policy). Next.js merges
// metadata shallowly, so `openGraph` / `twitter` set here fully replace the
// layout's homepage values; every field the layout sets is repeated here with
// this page's own title, description and URL. That replacement also drops the
// image generated by app/[locale]/opengraph-image.tsx (it's attached to the
// layout segment's openGraph), so the same image is referenced explicitly.
export async function generateServicePageMetadata(
  locale: string,
  path: string,
  title: string,
  description: string,
): Promise<Metadata> {
  const languages = Object.fromEntries(routing.locales.map((l) => [l, `/${l}${path}`]));
  const url = `/${locale}${path}`;
  // Same values as app/[locale]/opengraph-image.tsx (size / alt / contentType).
  const image = {
    url: `/${locale}/opengraph-image`,
    width: 1200,
    height: 630,
    alt: "Vekaro",
    type: "image/png",
  };

  return {
    title,
    description,
    alternates: {
      canonical: url,
      languages: {
        ...languages,
        "x-default": `/${routing.defaultLocale}${path}`,
      },
    },
    openGraph: {
      title,
      description,
      url,
      siteName: "Vekaro",
      locale: OG_LOCALES[locale] ?? "en_US",
      type: "website",
      images: [image],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [image],
    },
  };
}
